### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by JamesParkDev** [BlackB1RD-Development/JetLogger#2]
Would this be good to introduce having an ability to create a preset instead of having to configure it every time?

Examples:
- You need to create a file named `jetlogger.settings.json`

File:
```json
{
  "theme": ["cool-logger"]
}
```

You just need to do `npm i cool-logger` or `yarn add cool-logger` if you like to use more of yarn.

This means that everyone can create their own themes and post them as packages that others can download. Maybe even adding more settings to configure from the file?

**Comment by RealBlackB1RD** [comment]
A more easy thing to do is just making a pull request each time you want to publish a new Logger theme to the
